### ISSUE TITLE
Improve login page UI

### ISSUE THREAD

**Issue by AK04** [AK04/ktu-activity-points#1]
Login page looks rather dull. Improve the UI with bootstrap.
The page is located at views/Login/index.php

**Comment by James-N-M** [comment]
@AK04 ill claim this and give it a go

**Comment by AK04** [comment]
@James-N-M Great! Please make a new branch and commit your changes. :D

**Comment by AK04** [comment]
@James-N-M Hey, If you are not working on it please do tell me.

**Comment by James-N-M** [comment]
@AK04 I couldn't think of a way to update the UI on the page. So I'm not working on it

**Comment by mikgross** [comment]
@AK04 I can give it a shot if still opened

**Comment by AK04** [comment]
@mGrossSRT Great! Let me know if you need any help!
You really don't need to download the repo and setup the whole thing. You can just copy the code in views/Login/index.php and paste it in codepen.io and make changes.

**Comment by mGrossSRT** [comment]
https://codepen.io/mgrosssrt/pen/zjqoNg
